activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 128 # 16
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 4.0
dataset: QM9
dataset_arg: energy_U0
dataset_root: data
derivative: false
distance_influence: both
distributed_backend: ddp_cpu
early_stopping_patience: 30
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
embedding_dimension: 8 # 128 - must be a multiple of 8
energy_files: null
energy_weight: 1.0
force_files: null
force_weight: 1.0
inference_batch_size: 16
load_model: models/model.ckpt
save_dir: models
lr: 0.0001
lr_factor: 0.8
lr_min: 1.0e-06
lr_patience: 10
lr_warmup_steps: 0
max_num_neighbors: 32 # 32
max_z: 100 # 100
neighbor_embedding: true
ngpus: 0
num_epochs: 1
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 10 # 20
num_workers: 4
output_model: Scalar
precision: 32
prior_model: Atomref
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 1
seed: 1
splits: null
standardize: false
test_interval: 5
test_size: 512
train_size: 256 # 110000
trainable_rbf: false
val_size: 256 # 10000
weight_decay: 0.0
