name: "Run tests"

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env create --file environment.yml --name base python=3.8
        C:\Miniconda\condabin\conda.bat install --file requirements.txt
        C:\Miniconda\condabin\conda.bat install pytorch torchvision torchaudio cpuonly -c pytorch
        C:\Miniconda\condabin\conda.bat info --envs
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Test with pytest
      run: |
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install pytest
        pytest --verbose

