name: "Run tests"

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env create --name base python=3.8
        C:\Miniconda\condabin\conda.bat init powershell
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install pytorch torchvision torchaudio cpuonly -c pytorch
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.1+cpu.html
        pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.1+cpu.html
        pip install torch-cluster -f https://data.pyg.org/whl/torch-1.10.1+cpu.html
        pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.10.1+cpu.html
        pip install torch-geometric
    - name: Test with pytest
      run: |
        C:\Miniconda\condabin\conda.bat info --envs
        C:\Miniconda\condabin\conda.bat activate base
        pytest --verbose