name: "Run tests"

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file environment.yml --name dtu_mlops_pytorch_geometric python=3.8
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Test with pytest
      run: |
        C:\Miniconda\condabin\conda.bat activate dtu_mlops_pytorch_geometric
        C:\Miniconda\condabin\conda.bat install pytest
        pytest --verbose

